"""``GET|POST /api/search`` - SerpApi powered shopping search."""

from __future__ import annotations

import logging

from fastapi import APIRouter, Body, File, Form, Query, UploadFile

from app.models.product import SearchResponse
from app.models.search import SearchRequest
from app.services import lens_service, product_service
from app.services.visual_rerank_service import rerank
from app.services.serpapi_service import clear_cache
from app.utils.images import prepare_image, validate_upload
from app.utils.errors import InvalidImageError

logger = logging.getLogger("snapbuy.routes.search")

router = APIRouter(tags=["search"])


async def _search(
    request: SearchRequest, *, sort_by: str | None = None, search_mode: str = "text"
) -> SearchResponse:
    logger.info(
        "Search query=%r limit=%s sort_by=%r search_mode=%r",
        request.query,
        request.limit,
        sort_by,
        search_mode,
    )
    response = await product_service.search_products(
        request.query,
        limit=request.limit,
        gl=request.gl,
        hl=request.hl,
        force_refresh=request.force_refresh,
        sort_by=sort_by,
        search_mode=search_mode,
    )
    logger.info(
        "Search finished query=%r products=%s demo=%s in %sms",
        request.query,
        len(response.products),
        response.is_demo,
        response.elapsed_ms,
    )
    return response


@router.post("/search", response_model=SearchResponse, summary="Search shopping results")
async def search_post(
    request: SearchRequest = Body(
        ...,
        examples=[{"query": "Nike Air Max 270 black men's shoes"}],
    ),
) -> SearchResponse:
    return await _search(request, search_mode="text")


@router.post(
    "/search-with-image",
    response_model=SearchResponse,
    summary="Search and visually rerank shopping results",
)
async def search_with_image(
    file: UploadFile = File(...),
    query: str = Form("", max_length=300),
    limit: int = Form(40, ge=1, le=60),
    force_refresh: bool = Form(False),
) -> SearchResponse:
    """Image-guided search: fetch shopping results then rerank by CLIP similarity.

    The query is expected to have been generated by the vision pipeline
    (OWL-ViT / hosted provider) or provided by the user. If omitted or empty,
    Google Lens visual similarity is checked to extract a suitable query.
    """
    data = await file.read()
    validate_upload(file.filename, file.content_type, data)
    if not data:
        raise InvalidImageError("The uploaded file was empty.")

    prepared = prepare_image(data, file.content_type)
    target_query = query.strip()
    if not target_query or target_query.lower() in ("visually similar products", "visual search"):
        try:
            lens_res = await lens_service.visual_similar_for_image(prepared)
            if lens_res.matches:
                target_query = lens_res.matches[0].title
            else:
                import re
                clean = re.sub(r'[-_.]', ' ', (file.filename or '').rsplit('.', 1)[0]).strip()
                target_query = clean or "product"
        except Exception:
            import re
            clean = re.sub(r'[-_.]', ' ', (file.filename or '').rsplit('.', 1)[0]).strip()
            target_query = clean or "product"

    logger.info(
        "search-with-image query=%r bytes=%s limit=%s",
        target_query,
        len(data),
        limit,
    )

    response: SearchResponse | None = None
    try:
        response = await _search(
            SearchRequest(query=target_query, limit=limit, force_refresh=force_refresh),
            sort_by="review_count",
            search_mode="image",
        )
    except Exception as exc:
        logger.warning(
            "Shopping search failed during image search (%s); falling back to Google Lens visual matches",
            exc,
        )
        try:
            lens_res = await lens_service.visual_similar_for_image(prepared)
            if lens_res.matches:
                from datetime import datetime, timezone
                from app.models.product import Product
                from app.services.summary_service import compute_summary

                fallback_products = [
                    Product(
                        id=m.id,
                        title=m.title,
                        price=m.price,
                        currency=m.currency,
                        price_formatted=m.price_formatted,
                        source=m.source or "Google Lens",
                        thumbnail=m.thumbnail,
                        link=m.link,
                        rating=m.rating,
                        match_label="Google Lens Match",
                        ranking_score=0.9,
                        is_demo=lens_res.is_demo,
                    )
                    for m in lens_res.matches
                ]
                summary = compute_summary(fallback_products)
                return SearchResponse(
                    query=target_query or (lens_res.matches[0].title if lens_res.matches else "Product"),
                    timestamp=datetime.now(timezone.utc),
                    summary=summary,
                    products=fallback_products,
                    search_mode="image",
                    is_demo=lens_res.is_demo,
                    notes=["Loaded visual matches directly from Google Lens."],
                )
        except Exception:
            pass
        raise exc

    # If Google Shopping returned 0 products for the query, supplement from Google Lens visual matches
    if not response.products:
        try:
            lens_res = await lens_service.visual_similar_for_image(prepared)
            if lens_res.matches:
                from datetime import datetime, timezone
                from app.models.product import Product
                from app.services.summary_service import compute_summary

                fallback_products = [
                    Product(
                        id=m.id,
                        title=m.title,
                        price=m.price,
                        currency=m.currency,
                        price_formatted=m.price_formatted,
                        source=m.source or "Google Lens",
                        thumbnail=m.thumbnail,
                        link=m.link,
                        rating=m.rating,
                        match_label="Google Lens Match",
                        ranking_score=0.9,
                        is_demo=lens_res.is_demo,
                    )
                    for m in lens_res.matches
                ]
                summary = compute_summary(fallback_products)
                return SearchResponse(
                    query=target_query or (lens_res.matches[0].title if lens_res.matches else "Product"),
                    timestamp=datetime.now(timezone.utc),
                    summary=summary,
                    products=fallback_products,
                    search_mode="image",
                    is_demo=lens_res.is_demo,
                    notes=["Found visual matches directly from Google Lens."],
                )
        except Exception:
            pass

    products, notes = await rerank(response.products, prepared)
    response.products = products
    response.notes.extend(notes)

    scored_count = sum(
        1 for p in products if p.visual_similarity_score is not None
    )
    logger.info(
        "Visual-rerank finished query=%r scored=%s/%s",
        target_query,
        scored_count,
        len(products),
    )
    response.search_mode = "image"
    return response


@router.get("/search", response_model=SearchResponse, summary="Search shopping results (query string)")
async def search_get(
    q: str = Query(..., min_length=1, max_length=300, description="Product search query"),
    limit: int = Query(40, ge=1, le=60),
) -> SearchResponse:
    return await _search(SearchRequest(query=q, limit=limit), search_mode="text")


@router.delete("/search/cache", summary="Clear the backend search cache", include_in_schema=False)
async def clear_search_cache() -> dict[str, str]:
    clear_cache()
    return {"status": "cleared"}
